name: AI Coder Bot   # The name of this workflow (shows up in GitHub Actions tab)

on:
  issues:
    types: [opened, edited]  
    # 👆 This means: every time you open or edit an Issue in GitHub,
    # this workflow will run and try to make code changes.

permissions:
  contents: write        # Bot can push code to a branch
  pull-requests: write   # Bot can open pull requests

jobs:
  ai_coder:
    runs-on: ubuntu-latest   # Runs on a Linux virtual machine in GitHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # 👆 This pulls your repo code into the GitHub Action so the bot can see it.

      - name: Run OpenAI (AI Coder)
        id: ai
        uses: Just-Moh-it/openai@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-mode: "chat"
          openai-params: >
            {
              "model":"gpt-4",
              "messages":[
                {"role":"system","content":"You are an AI programmer. Edit the repo code to solve the issue described."},
                {"role":"user","content":"${{ github.event.issue.body }}"}
              ],
              "max_tokens":2000
            }
        # 👆 This step calls OpenAI with your API key.
        # It sends the Issue text to GPT and asks for code changes.

      - name: Save AI Patch
        run: |
          echo "${{ steps.ai.outputs.completion }}" > ai_patch.diff
        # 👆 Whatever GPT outputs gets saved as a patch file.

      - name: Commit AI changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "AI Coder Bot"
          git checkout -b "ai-fix-${{ github.event.issue.number }}"
          git apply ai_patch.diff || echo "No changes applied"
          git commit -am "AI fix for Issue #${{ github.event.issue.number }}" || echo "Nothing to commit"
          git push origin HEAD
        # 👆 This creates a new branch, applies the patch, commits it, and pushes.

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "AI Fix: ${{ github.event.issue.title }}"
          body: "This PR was auto-generated by the AI Coder Bot based on your issue."
          branch: "ai-fix-${{ github.event.issue.number }}"
        # 👆 This opens a pull request for you to review/merge.
