name: AI Coder Bot
on:
  issues:
    types: [opened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  generate_patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate AI fix
        uses: Just-Moh-it/openai@v0.0.1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          openai-mode: "chat"
          openai-params: >
            {"prompt":"Please modify the code according to the issue: ${{ github.event.issue.body }}","model":"gpt-4","max_tokens":2000}

      - name: Commit AI changes
        run: |
          echo "${{ steps.openai.outputs.completion }}" > ai_patch.diff
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "AI Coder Bot"
          git checkout -b "ai-fix-${{ github.event.issue.number }}"
          git apply ai_patch.diff
          git commit -a -m "AI fix for: #${{ github.event.issue.number }}"
          git push origin HEAD

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "AI Fix: ${{ github.event.issue.title }}"
          body: "This PR was auto-generated by the AI Coder Bot based on your issue."
          branch: "ai-fix-${{ github.event.issue.number }}"
